sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.2
notifications:
  slack:
    secure: "iKoW31B15AOmHpz9oI+7tfGwQhZBDhrcGU0tigkmuisK8cxCQu409UPA6AAjL+VHMh1n74STqDpCD1BP+5i83PSk8caPqowZGqwMjUyYinvT20AC9oV7xyg/wWv95aeLmczOEZqPKTnS+otF6gysq/P7b6F5/g6hCegS+q3/DRHIb6DIIlg7+YKnNGwxQeI3QhP1UvIl3Hf5GxcDiQYO/O9yHKToXF6FJvZTaEPm98WmnJtcrs60ou5D/RpPiyy4gpacMvs7aQknya6PbdHtCuaKXBHibXHhCQrvzeBc5ccG3DcjzzLVVMHvPKQLT4NS8wMwDPcIhOSsXKK/aSm2WIh5i+lIPGAvMLTQqTryWjcgygxPqNa2PLIdN/z2bhTJ8tmtwGZ3lOScN9SjEK1o8PpmslEgKsoJiUYiMHFy+akc6xpcoR/QD8T2nWPTj7fMOzf9UZO8eS6XJ5f2faQ87CbD1v9FTm0oJrJew10uAC3jxevx7J/8sfNcR2VF+cKSZ4R3hc00Xh/Qcrk8iv/77d8jkxXtYkbZkYCftWTGdQk/13UHI/uwaDB1YDKDz1GkPYQK5YVkAzdRy9mnhgkf1WXJDyIRieswgyeSBzmvyuPZWPWMmNEOGg5aG57DbLTLLPnda1euL5iOTQrYV1FnNBXSClJ6DzG6s5c9wQRAW84="

    on_success: change
    on_failure: always
deploy:
  provider: rubygems
  gem: getto-initialize_with
  on:
    tags: true
  api_key:
    secure: "ZyXduNzZ7KYXpJ72KLriIiFwVUN9ZEHsKeF0Luvk/PQb9efFewO1xx31BhJi8aYeiAVqY8WdWmbEXUS9CviWiyAhdQhb6Z7CgpnXNbLwBVarlXbAe4KbHxlbHRTf8OeVATw76uaCPafIB3l1tSkrWNhILD+FIHWsUcj4+lH43LA0oLCMB5o79rH1jwHjDVXIatARpVqpwgfoz/KJsVtqaJgIX5vU+ae5D4INCqD5T4mSbTKp4Li32YpMrAxR3IUuPR1CJAcfCLC6Yy0yjGUi7QpbCQkLzjJ0wu1OYq8CjLc8sU+4ifnc7VymWrF3FmvEDi4tjSlU+oFrc2C0tsT9JUUPZDcIlJ6yQ1oJ6uSC9SIYJwTCR/n+yZ6Vk32sqEr90ZLdUyXIZHwk/TaxU0GqFNqyTKFEgzhGZDnxq98AG5PRgu0OIOa1KqPCiyCyIYLa/ffiPjHk++ztv8aTErBkL03gqrNAHXDdXm6uruABP0fl1J7z+MqNFs5zJgHHCSKSiYVPng2VTUuYazaJvup0qlfVVENxV/Bgz52/bz0QMI4OIaWDhC/cky9DPn7k0AcgVDFSdcDzIfZu7jqK2uqssE8lgxzHab9p9oXeTMPJTLVKS8bpLF1yiuCgBOczYLKZBfjT0tY4hiCOmQCfVgaijXj2VwQ7OwzdWhOndROrofM="
